#!/bin/bash
set -e

# -- Config --
programmer="-p /dev/ttyUSB0"
#programmer="-P usbasp"

# Board versions
# Don't forget to update board voltage too!
# Arduino pro mini 3,3V 8MHz
#board_name="arduino:avr:pro:cpu=8MHzatmega328"
# Arduino pro mini 5V 16MHz
board_name="arduino:avr:pro:cpu=16MHzatmega328"

app_name=gardensensor

libraries="./libraries/KnxTpUart"

# -- Run --
echo "== Compiling application ${app_name} for board ${board_name}..."
arduino-cli compile -v --libraries ${libraries} --fqbn ${board_name} ${app_name}
echo "== Compile done."
echo
echo "== Flashing binary to board ${board_name}... "
arduino-cli upload -v ${programmer} --fqbn ${board_name} ${app_name}
echo "== Flashing done."


