#!/bin/bash
set -e

# -- Config --
programmer="/dev/ttyUSB0"
#programmer="usbasp"
board_name="arduino:avr:pro:cpu=8MHzatmega328"
app_name=gardensensor

# -- Run --
echo "== Compiling application ${app_name} for board ${board_name}..."
arduino-cli compile -v --fqbn ${board_name} ${app_name}
echo "== Compile done."
echo
echo "== Flashing binary to board ${board_name}... "
arduino-cli upload -p ${programmer} --fqbn ${board_name} ${app_name}
echo "== Flashing done."


